// Autogenerated from Pigeon (v9.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by MessageApi.
NSObject<FlutterMessageCodec> *MessageApiGetCodec(void);

@protocol MessageApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getMessageText:(NSString *)text error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void MessageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessageApi> *_Nullable api);

NS_ASSUME_NONNULL_END
